{
    'name': 'App One',
    'author': 'Eslam Mohamed',
    'version': '17.0',
    'category': '',
    'depends': ['base', 'sale_management', 'account', 'mail', 'contacts', 'hr'
                ],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/base_menu.xml",
        "views/property_view.xml",
        "views/owner_view.xml",
        "views/tag_view.xml",
        "views/sale_order_view.xml",
        "views/res_partner_view.xml",
        "views/building_view.xml",
        "views/property_history_view.xml",
        "views/account_move_view.xml",
        "views/hr_employee_view.xml",
        "views/hr_employee_view.xml",
        "wizard/change_state_wizard_view.xml",
        "reports/property_report.xml",
        "reports/account_invoice_report_inherit.xml",
    ],
    'assets': {
        'web.assets_backend': ['app_one/static/src/css/property.css'],
        'web.report_assets_common': ['app_one/static/src/css/font.css'],
    },
    'application': True,
}
